version: '3'

networks:
  laravel:

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name : nginx
    ports:
    - 8080:80
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/access_log/:/var/log/nginx/
    - $PWD:/var/www/html/hoory
    tty: true
    depends_on:
      - php
    networks:
      laravel:

  php:
    build:
      context: php
      dockerfile: Dockerfile
    container_name : php
    tty: true
    ports:
    - 9000:9000
    volumes:
    - $PWD:/var/www/html/hoory
    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      laravel:

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: redis
    tty: true
    networks:
      laravel:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hoory
    networks:
      laravel:

